# WorldForge/src/docker-compose.yml

services:
  backend:
    build:
      context: ./backend  # backend 디렉터리 경로
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # 백엔드 FastAPI 서버 포트
    env_file:
      - .env  # .env 파일 참조
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - UPSTAGE_API_KEY=${UPSTAGE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    depends_on:
      - frontend  # 백엔드가 프론트엔드와 의존관계 설정

  frontend:
    build:
      context: ./frontend # frontend 디렉터리 경로
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # 프론트엔드 서버 포트